// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlgdpudyibttlmskvuic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZ2RwdWR5aWJ0dGxtc2t2dWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTYxNDUsImV4cCI6MjA3MDg3MjE0NX0.AxnikoOzWETx6taLuo5Wtl6ptYMacjD0vaKhaPs3Xrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});